import type { Creator, Project, SocialAccount, Publishability } from "../../domain/creator";
import { api } from "../api/apiClient";
type RawCreator = Record<string, any>;
const mapProject = (p: any): Project => ({ id: p.id, title: p.title, description: p.description || "", type: p.type || "Project", url: p.url, createdAt: p.created_at, updatedAt: p.updated_at });
const mapSocial = (s: any): SocialAccount => ({ id: s.id, platform: s.platform, username: s.username, profileUrl: s.profile_url, verificationStatus: s.verification_status, ownershipVerified: Boolean(s.ownership_verified), eligibilityVerified: Boolean(s.eligibility_verified), followerCount: s.eligibility_verified ? s.follower_count : undefined, verifiedAt: s.verified_at || undefined });
export const mapCreator = (c: RawCreator): Creator => ({ id: c.id, displayName: c.display_name, username: c.username, bio: c.bio || "", avatar: c.avatar || "", location: c.location || undefined, website: c.website || undefined, categories: c.categories || [], skills: c.skills || [], lookingFor: c.looking_for || [], projects: (c.projects || []).map(mapProject), socialAccounts: (c.social_accounts || []).map(mapSocial), createdAt: c.created_at, updatedAt: c.updated_at, publishability: c.publishability || { publishable: false, missing: [] } });
export async function listCreators(query: { search: string; category: string; sort: string }) { const q = new URLSearchParams({ limit: "30", sort: query.sort }); if (query.search) q.set("search", query.search); if (query.category) q.set("category", query.category); const result = await api<{ creators: RawCreator[]; total: number }>(`/api/creators?${q}`); return { creators: result.creators.map(mapCreator), total: result.total }; }
export async function getCreator(username: string) { return mapCreator((await api<{ creator: RawCreator }>(`/api/creators/${encodeURIComponent(username)}`)).creator); }
export async function getMyCreator() { const result = await api<{ creator: RawCreator | null }>("/api/creator/me"); return result.creator ? mapCreator(result.creator) : null; }
export type CreatorInput = { displayName: string; username: string; bio: string; avatar: string; location: string; website: string; categories: string[]; skills: string[]; lookingFor: string[]; };
const creatorPayload = (v: CreatorInput) => ({ display_name: v.displayName, username: v.username, bio: v.bio, avatar: v.avatar, location: v.location || null, website: v.website || null, categories: v.categories, skills: v.skills, looking_for: v.lookingFor });
export async function saveCreator(input: CreatorInput, exists: boolean) { const result = await api<{ creator: RawCreator }>("/api/creator", { method: exists ? "PATCH" : "POST", body: JSON.stringify(creatorPayload(input)) }); return mapCreator(result.creator); }
export async function getStatus() { return api<Publishability>("/api/creator/status"); }
export async function createProject(input: Omit<Project, "id">) { return mapProject((await api<{ project: any }>("/api/creator/projects", { method: "POST", body: JSON.stringify(input) })).project); }
export async function updateProject(id: number, input: Omit<Project, "id">) { return mapProject((await api<{ project: any }>(`/api/creator/projects/${id}`, { method: "PATCH", body: JSON.stringify(input) })).project); }
export async function deleteProject(id: number) { await api(`/api/creator/projects/${id}`, { method: "DELETE" }); }
export async function createSocial(input: Pick<SocialAccount, "platform" | "username" | "profileUrl">) { return mapSocial((await api<{ social_account: any }>("/api/creator/socials", { method: "POST", body: JSON.stringify({ platform: input.platform, username: input.username, profile_url: input.profileUrl }) })).social_account); }
export async function updateSocial(id: number, input: Pick<SocialAccount, "platform" | "username" | "profileUrl">) { return mapSocial((await api<{ social_account: any }>(`/api/creator/socials/${id}`, { method: "PATCH", body: JSON.stringify({ platform: input.platform, username: input.username, profile_url: input.profileUrl }) })).social_account); }
export async function deleteSocial(id: number) { await api(`/api/creator/socials/${id}`, { method: "DELETE" }); }
