[alembic]
script_location = migrations
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic
[handlers]
keys =
[formatters]
keys = generic
[logger_root]
level = WARN
handlers =
[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
[logger_alembic]
level = INFO
handlers =
qualname = alembic
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
